on:
  push:
    branches:
      - master
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            app/nflstream/node_modules
            app/node_modules
          key: v1
          restore-keys: |
            v1

      - run: bash .github/workflows/record_sha.sh
      - run: bash .github/workflows/build_react.sh
      - run: bash .github/workflows/deploy_to_firebase.sh '${{ secrets.SA_KEY }}'
